- name: 'Create new AD forest {{ ad.domain }}'
  win_shell: |
    Import-Module ADDSDeployment

    Install-ADDSForest                                                        \
      -DomainName "{{ ad.domain }}"                                           \
      -CreateDnsDelegation:$false                                             \
      -DomainNetbiosName "{{ ad.netbios }}"                                   \
      -ForestMode "{{ ad.forest_mode }}"                                      \
      -DomainMode "{{ ad.domain_mode }}"                                      \
      -Force:$true                                                            \
      -InstallDns:$true                                                       \
      -NoRebootOnCompletion:$true                                             \
      -SafeModeAdministratorPassword                                          \
        (ConvertTo-SecureString '{{ ad.safe_password }}' -AsPlainText -Force)
  register: installation
  args:
    creates: 'C:\Windows\NTDS'

- name: Reboot machine
  win_reboot:
  when: installation.changed
