---
- hosts: scheduler
  remote_user: root
  name: deploy open_close_pr tool
  gather_facts: yes
  vars:
    repo_name: freeipa

  vars_prompt:
    - name: identifier
      prompt: "Provide an unique identifier for the PR"
      private: false

    - name: flow
      prompt: "Flow name to identify the nightly template: ci or pki"
      private: false
      default: "ci"

    - name: branch
      prompt: "Branch name to open PR against it"
      private: false

    - name: repo_owner
      prompt: "Repo owner to create branches"
      private: false
      default: "freeipa-pr-ci"

    - name: github_token
      prompt: "GitHub token"
      private: false

    - name: prci_config
      prompt: "Provide the path to a test definition file to use it to open new
               PRs. For example: ipatests/prci_definition/gating"
      private: false

    - name: git_sshkey
      prompt: "Provide a ssh key that has push access to the git repo"
      private: false

    - name: pr_against_upstream
      prompt: "Should the PR be open against the upstream repo?. Type no for
               opening it agaist your own freeipa repo (yes/no)"
      private: false

    - name: prci_def_dir
      prompt: "Provide PRCI test definitions folder.
               E.g. ipatests/prci_definition"
      private: false

    - name: fedora_ver
      prompt: "Provide Fedora version (int) for template creation. E.g. 29"
      private: false

    - name: vagrant_atlas_token
      prompt: "Provide Vagrant atlas token for uploading boxes"
      private: false

  pre_tasks:
    - name: install python and deps for ansible modules
      raw: dnf install -y python2 python2-dnf libselinux-python

  roles:
    - role: automation/setup
      when: >
            prci_config != "" and github_token != "" and
            identifier != "" and  repo_owner != 'freeipa'
    - role: automation/nightly_pr
    - role: automation/template_pr
